### ISSUE TITLE
GitLab CI job disappears from pipeline

### ISSUE THREAD

**Issue by jangrewe** [gabrie-allaigre/sonar-gitlab-plugin#121]
Hi,
your plugin is working great, except for one small (cosmetic) issue: After the scan has ran, the "External" job is created, and the original job disappears from the Pipeline view:

![Pipeline](https://screenshotscdn.firefoxusercontent.com/images/42231ce7-973a-44ae-8104-c2dbdeec4db4.png)

I have to go to the Jobs list to find the job again. Is there any way to fix this?

**Comment by gabrie-allaigre** [comment]
Hi,
Can you get file .gitlab-ci.yml ?
Thanks

**Comment by jangrewe** [comment]
Sure, here's a "sanitized" version:
```
stages:
  - test
  - docker
  - build
  - deploy

sonarqube:
  image: registry.example.com/sonar-scanner
  stage: test
  script:
    - sonar-scanner -Dsonar.projectBaseDir=$(pwd) -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME} -Dsonar.gitlab.project_id=${CI_PROJECT_ID}
    - sonar-scanner -Dsonar.projectBaseDir=$(pwd) -Dsonar.projectVersion=${CI_COMMIT_SHA}

build_deploy:
  stage: docker
  when: manual
  script:
    - docker build -t registry.example.com/build -f Dockerfile.deploy .
    - docker push registry.example.com/build
```
