### ISSUE TITLE
WARNING: codeclimate.json: no matching files 

### ISSUE THREAD

**Issue by adamparmelee** [gabrie-allaigre/sonar-gitlab-plugin#141]
after my CI runs I'm able to see results in sonarqube, but codeclimate.json isn't being created...

here's what I'm running in gitlab-ci.yml

sonarqube_preview_feature_job:
  stage: test
  only:
    - sonarqube
  script:
    - git checkout origin/master
    - git merge $CI_COMMIT_SHA --no-commit --no-ff
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.projectKey=UI -Dsonar.sources=src -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.json_mode=CODECLIMATE -Dsonar.gitlab.failure_notification_mode=commit-status
  artifacts:
    expire_in: 1 day
    paths:
      - codeclimate.json

**Comment by iluwaa** [comment]
i have a same problem, fixed with plugin update

**Comment by Poeschl** [comment]
Having the same issue, where no `codeclimate.json` is generated.

My `gitlab-ci.yml` config is:

```yml
sonarqube analysis preview:
  stage: analysis
  except:
  - master
  tags:
  - aws
  image: gradle:4.8.1-jdk8
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
  - >
    gradle -info -Dsonar.login=$SONAR_LOGIN_TOKEN -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview
    -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
    -Dsonar.gitlab.json_mode=CODECLIMATE -Dsonar.gitlab.failure_notification_mode=commit-status
    sonarqube
  - ls -al
  artifacts:
    expire_in: 1 day
    paths:
    - codeclimate.json
```
