### ISSUE TITLE
Master branch CI build status is failed even though branch build passed with preview analysis

### ISSUE THREAD

**Issue by amimas** [gabrie-allaigre/sonar-gitlab-plugin#143]
Hello,

I have the plugin setup and working. My `gitlab-ci.yml` file looks like this:

```yml
stages:
        - build
        - validation

sonarqube_preview:
        stage: validation
        script:
                - sh gradlew sonarqube -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        except:
                - master

sonarqube:
        stage: validation
        script:
                - sh gradlew sonarqube
        only:
                - master
```

This works fine. I wanted to clean up the script a little bit. So, I moved the `sonar.gitlab.xxx` properties from `gitlab-ci.yml` file to my gradle script, whose snippet is below:

new `gitlab-ci.yml` script:

```yml
stages:
        - build
        - validation

sonarqube_preview:
        stage: validation
        script:
                - sh gradlew sonarqube -Dsonar.analysis.mode=preview
        except:
                - master

sonarqube:
        stage: validation
        script:
                - sh gradlew sonarqube
        only:
                - master
```
`build.gradle` script:

```gradle
sonarqube {
   properties {
		property 'sonar.gitlab.project_id', System.getenv("CI_PROJECT_ID")
		property 'sonar.gitlab.commit_sha', System.getenv("CI_COMMIT_SHA")
		property 'sonar.gitlab.ref_name', System.getenv("CI_COMMIT_REF_NAME")
   }
}
```
However now, with the pipeline of the master branch is keep failing. It's reporting something like this in the failure:
```
SonarQube analysis indicates that quality gate is failed.

Security Rating on New Code is failed: Actual value 4 > 1
Reliability Rating on New Code is passed: Actual value 1
Maintainability Rating on New Code is passed: Actual value 1
SonarQube analysis reported 47 issues

⛔ 1 blocker
🚫 20 critical
⚠ 4 major
🔽 22 minor
```

With my new change, why is the master branch suddenly being reported as a failure? I understand the overall project quality did not pass, but my pipeline in Gitlab CI shouldn't be failing for the master branch.
