### ISSUE TITLE
External job is added to the wrong pipeline

### ISSUE THREAD

**Issue by danielvijge** [gabrie-allaigre/sonar-gitlab-plugin#211]
_This required Gitlab 11.6+ which supports the only: merge_requests syntax in the CI/CD pipeline._

**Description**
I want to set up a flow where the master branch is protected, development happens in feature branches, and everything is merged via merge requests in Gitlab. To achieve this, I want to run a preview analysis on every commit to a feature branch, so that comments are added to the commit. When there is a merge request, I want to run a full analysis, so that Sonarqube checks the quality gate, and can determine if the merge request is allowed to be merged.

This is a slightly modified configuration of the one mentioned in the readme:
```
sonarqube_master_job:
  stage: test
  only:
    - merge_requests
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME

sonarqube_preview_feature_job:
  stage: test
  only:
    - /^feature\/*/
  script:
    - git checkout origin/master
    - git merge $CI_COMMIT_SHA --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
```

The first time something is pushed to a feature branch, the preview analysis runs. This works as expected. Now when a merge request is created, the quality gate analysis runs. This also works as expected.
However, when there is an additional commit to the same feature branch that already has an open merge request, GitLab starts both the _sonarqube_master_job_ and the _sonarqube_preview_feature_job_. In general, this is OK, because it's new code, and I want both the comments and the quality gate.

In my tests, the _sonarqube_preview_feature_job_ is created with pipeline ID 1, the _sonarqube_master_job_ is created with pipeline ID 2. Pipeline 1 finishes first, but the external sonarqube step is added to pipeline 2. After pipeline 2 finishes, the external job is added to pipeline 2 as well. The external job for pipeline 1 is visible in pipeline 2 as a retried job.

My guess is that this is happening because only the CI_COMMIT_SHA and CI_COMMIT_REF_NAME are passed. But these are the same for both pipelines. No CI_PIPELINE_ID is passes, that tells the plugin to add it to the correct pipeline.

Jobs for the sonarqube_preview_feature_job:
<img width="1130" alt="screenshot 2019-01-21 at 13 53 15" src="https://user-images.githubusercontent.com/1246723/51475956-47436b00-1d84-11e9-94f9-65f197394d4d.png">

Jobs for the sonarqube_master_job:
<img width="1129" alt="screenshot 2019-01-21 at 13 53 46" src="https://user-images.githubusercontent.com/1246723/51475926-267b1580-1d84-11e9-9720-f7392bf2783b.png">

**Comment by danielvijge** [comment]
It's actually also possible to recreate this without merge requests, but with the only: web feature when running a manual pipeline. For example:

```
sonarqube_master_job:
  stage: test
  only:
    -  master
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME

sonarqube_preview_feature_job:
  stage: test
  only:
    - /^feature\/*/
  script:
    - git checkout origin/master
    - git merge $CI_COMMIT_SHA --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  only:
  - web
  script:
  - do_deployment
```
When manually running a pipeline on a branch that has already an active pipeline with a Sonarqube check, the results is that the external stage is added to the deploy pipeline (even though that pipeline doesn't have a Sonarqube job at all.
