### ISSUE TITLE
Is this plugin usable for MSBuild and C# project?

### ISSUE THREAD

**Issue by rpiesnikowski** [gabrie-allaigre/sonar-gitlab-plugin#42]
Hi,
Can I use this plugin with .NET repositories? Some workarounds to wrap MSBuild in mvn? Or there is diffrent approach?
I've tried example mvn commands but without success (which is obvious mvn is for Java).

**Comment by gabrie-allaigre** [comment]
Hi,
Use sonar scanner for msbuild

**Comment by K3UL** [comment]
I can report I used it with succes with Sonar Scanner for MSBuild.
The job in the YAML looks something like that :

```yaml
Binaries:MSBuildAndSonar:
  stage: Build
  script: 
    - 'SonarQube.Scanner.MSBuild begin /k:"$env:ProjName" /n:"$env:ProjName" /v:"1.0" /d:sonar.gitlab.project_id=$CI_PROJECT_ID /d:sonar.gitlab.commit_sha=$CI_BUILD_REF /d:sonar.gitlab.ref_name=$CI_BUILD_REF_NAME /d:sonar.analysis.mode="preview"'
    - 'msbuild "$env:ProjFile" /p:Configuration=Release /p:Platform="x86" /p:AllowedReferenceRelatedFileExtensions=none /p:DebugSymbols=false /p:DebugType=None /p:Optimize=true /p:OutputPath="bin/Release/"'
    - 'SonarQube.Scanner.MSBuild end'
  tags:
  - csharp
  - windows
```
