### ISSUE TITLE
Error in master branch: The GitLab plugin is only intended to be used in preview or issues mode

### ISSUE THREAD

**Issue by wachri** [gabrie-allaigre/sonar-gitlab-plugin#87]
We have two different configs (like in the readme). One for feature branches and one for the master. The feature branches work really great with comments in GitLab etc. (runs in the preview mode). But for the master build, where we like to do a real scan with coverage and quality gates, we are getting an error:

```
ERROR: Error during SonarQube Scanner execution
ERROR: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder
ERROR: Caused by: The GitLab plugin is only intended to be used in preview or issues mode. Please set 'sonar.analysis.mode'.
```

The gitlab-ci.yml config for that job looks like:
```
sonarqube:
  <<: *node_cache
  <<: *before_test
  stage: quality
  image: ***
  dependencies:
  - unittest-chrome
  script:
  - export VERSION=$(./deploy/scripts/git-version)
  - sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.projectVersion=$VERSION -Dsonar.branch.name="$CI_COMMIT_REF_NAME" -Dsonar.projectKey='project-name' -Dsonar.projectName="Project Name" -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  only:
  - master
  except:
  - tags
```

Is there a way / option to bring that to work without an error at the end? 

### Versions
* Sonar: 6.7.0
* Plugin: 2.1.0
* GitLab: 10.2.4
