### ISSUE TITLE
fatal: repository not found when cloning

### ISSUE THREAD

**Issue by evbo** [gabrie-allaigre/sonar-gitlab-plugin#98]
Hi, I have followed the readme for setting up this plugin but am unable to run a job due to the below failure. What mistake did I make in configuration?

Job Failure:
```
Running with gitlab-runner 10.4.0 (857480b6)
  on sonarQube (d6cac072)
Using Shell executor...
Running on servername.com...
Cloning repository...
Cloning into '/home/gitlab-runner/builds/d6cac072/0/group/projectname'...
fatal: repository 'http://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@servername.com/group/projectname.git/' not found
ERROR: Job failed: exit status 1
```

I created a "sonar" user in gitlab with developer role. I set the token in my sonar user that was created for that same user.

My GitLab url is set to:
```
http://servername.com:8088
```

My GitLab project id is set to (the repository):
```
git@servername.com:group/projectname.git
```

My .gitlab-ci.yml is:
```
sonarqube_preview:
  script:
    - git checkout origin/master
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  except:
    - develop
    - master
    - /^hotfix_.*$/
    - /.*-hotfix$/
  tags:
    - java

sonarqube:
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL
  stage: test
  only:
    - master
  tags:
    - java
```
